# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-15 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SanaPlus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation_admin_user',
            name='id',
            field=models.AutoField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
