# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-15 09:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SanaPlus', '0002_auto_20180915_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='relation_parent_user',
            fields=[
                ('id', models.AutoField(max_length=20, primary_key=True, serialize=False)),
                ('parent', models.IntegerField()),
                ('child', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='relation_admin_user',
            name='child',
        ),
        migrations.RemoveField(
            model_name='relation_admin_user',
            name='parent',
        ),
        migrations.DeleteModel(
            name='relation_admin_user',
        ),
    ]
