# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-23 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SanaPlus', '0005_auto_20180915_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='type_apps',
            fields=[
                ('id', models.AutoField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='user_token',
            name='id',
            field=models.AutoField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
