# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-23 05:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SanaPlus', '0006_auto_20180923_0911'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apps_token',
            fields=[
                ('id', models.AutoField(max_length=20, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=48, unique=True)),
                ('type_apps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SanaPlus.type_apps')),
                ('user_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
