# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-23 09:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SanaPlus', '0009_auto_20180923_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events_Apps',
            fields=[
                ('id', models.AutoField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('code', models.CharField(max_length=6, unique=True)),
                ('descrip', models.TextField()),
                ('date_create_Events', models.DateField()),
                ('apps_events', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SanaPlus.Apps_tokens_admin')),
            ],
        ),
    ]
