# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-25 11:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SanaPlus', '0010_events_apps'),
    ]

    operations = [
        migrations.CreateModel(
            name='Happening_Events',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('Events', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SanaPlus.Events_Apps')),
                ('apps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SanaPlus.Apps_tokens_admin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
