# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-30 06:08
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClickEvents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('json_format', django.contrib.postgres.fields.jsonb.JSONField()),
                ('date_visited', models.DateField()),
            ],
        ),
    ]
