# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-06 10:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SanaPlus', '0011_happening_events'),
        ('Reporting', '0002_clicked_events_varchar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clicked_Events',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('json_format', models.TextField()),
                ('date_visited', models.DateField()),
                ('token_apps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SanaPlus.Apps_tokens_admin')),
            ],
        ),
        migrations.DeleteModel(
            name='Clicked_Events_varchar',
        ),
        migrations.DeleteModel(
            name='ClickEvents',
        ),
    ]
