# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-07 06:23
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reporting', '0003_auto_20181006_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clicked_events',
            name='json_format',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
