# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-07 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reporting', '0004_auto_20181007_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clicked_events',
            name='json_format',
            field=models.TextField(),
        ),
    ]
