# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-09 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reporting', '0005_auto_20181007_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clicked_events',
            name='token_apps',
            field=models.IntegerField(),
        ),
    ]
