# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-14 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reporting', '0006_auto_20181009_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record_Events',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('json_format', models.TextField()),
                ('date_visited', models.DateTimeField()),
                ('token_apps', models.IntegerField()),
                ('token_events', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Clicked_Events',
        ),
    ]
