# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-17 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reporting', '0009_auto_20181017_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageRanking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Events_id', models.IntegerField()),
                ('date_visited', models.DateTimeField()),
                ('referrer', models.CharField(max_length=250)),
                ('urls', models.CharField(max_length=250)),
                ('title', models.TextField()),
            ],
        ),
    ]
