# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-20 06:43
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reporting', '0010_pageranking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Events_id', models.IntegerField()),
                ('date_reserve', models.DateTimeField()),
                ('json_fields', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.AlterField(
            model_name='pageranking',
            name='referrer',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='pageranking',
            name='title',
            field=models.TextField(blank=True),
        ),
    ]
