# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-20 07:51
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reporting', '0011_auto_20181020_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='seller',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Events_id', models.IntegerField()),
                ('date_sell', models.DateTimeField()),
                ('json_fields', django.contrib.postgres.fields.jsonb.JSONField()),
                ('price', models.DecimalField(decimal_places=12, max_digits=15)),
                ('Reservation_id', models.IntegerField()),
            ],
        ),
    ]
