# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-21 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reporting', '0012_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='price',
            field=models.CharField(max_length=50),
        ),
    ]
