# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-21 07:39
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reporting', '0013_auto_20181021_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visited_Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Event_id', models.IntegerField()),
                ('json_fields', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.AlterField(
            model_name='record_events',
            name='json_format',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
