# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-21 07:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reporting', '0014_auto_20181021_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record_events',
            name='token_apps',
        ),
    ]
