# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-21 08:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Reporting', '0015_remove_record_events_token_apps'),
    ]

    operations = [
        migrations.AddField(
            model_name='visited_product',
            name='date_visited',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
