# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-21 08:22
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reporting', '0016_visited_product_date_visited'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search_Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Event_id', models.IntegerField()),
                ('json_fields', django.contrib.postgres.fields.jsonb.JSONField()),
                ('date_visited', models.DateTimeField()),
            ],
        ),
    ]
