# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-21 08:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reporting', '0017_search_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record_events',
            old_name='token_events',
            new_name='id_Events',
        ),
    ]
