# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-24 09:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reporting', '0020_register_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manage_Device',
        ),
        migrations.RenameField(
            model_name='pagerank',
            old_name='date_visited',
            new_name='date_record',
        ),
        migrations.RenameField(
            model_name='register_user',
            old_name='date_visited',
            new_name='date_record',
        ),
        migrations.RenameField(
            model_name='reserve',
            old_name='date_reserve',
            new_name='date_record',
        ),
        migrations.RenameField(
            model_name='search_product',
            old_name='date_visited',
            new_name='date_record',
        ),
        migrations.RenameField(
            model_name='sell',
            old_name='date_sell',
            new_name='date_record',
        ),
        migrations.RenameField(
            model_name='visited_product',
            old_name='date_visited',
            new_name='date_record',
        ),
    ]
