# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-24 10:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reporting', '0021_auto_20181024_1239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagerank',
            old_name='Events_id',
            new_name='Event_id',
        ),
        migrations.RenameField(
            model_name='record_events',
            old_name='id_Events',
            new_name='Event_id',
        ),
        migrations.RenameField(
            model_name='reserve',
            old_name='Events_id',
            new_name='Event_id',
        ),
    ]
