# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-24 10:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reporting', '0022_auto_20181024_1335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sell',
            old_name='Events_id',
            new_name='Event_id',
        ),
    ]
