# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-28 08:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reporting', '0023_auto_20181024_1342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record_events',
            old_name='date_visited',
            new_name='date_record',
        ),
    ]
