# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-28 09:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reporting', '0024_auto_20181028_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record_events',
            old_name='json_format',
            new_name='json_fields',
        ),
    ]
